<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;

class DailySalesExport implements FromCollection, WithHeadings, WithMapping, WithStyles, WithTitle, WithCustomStartCell
{
    protected $dailySales;
    protected $date;
    protected $currency_symbol;
    protected $settings;

    public function __construct($dailySales, $date)
    {
        $this->dailySales = $dailySales;
        $this->date = $date;

        $this->currency_symbol = get_currency_symbol();
        $this->settings = \App\Models\SystemSetting::getSettings();
    }

    public function startCell(): string
    {
        return 'A11';
    }

    public function collection()
    {
        return $this->dailySales;
    }

    public function headings(): array
    {
        return [
            'Invoice #',
            'Time',
            'Cashier',
            'Payment Method',
            'Items',
            "Subtotal ($this->currency_symbol)",
            "Discount ($this->currency_symbol)",
            "Tax ($this->currency_symbol)",
            "Total ($this->currency_symbol)"
        ];
    }

    public function map($sale): array
    {
        return [
            $sale->invoice_number,
            \Carbon\Carbon::parse($sale->created_at)->format('h:i A'),
            $sale->cashier->name ?? 'N/A',
            ucfirst($sale->payment_method),
            $sale->items->count(),
            (float)$sale->subtotal,
            (float)$sale->discount_amount,
            (float)$sale->tax_amount,
            (float)$sale->total_amount,
        ];
    }

    public function styles(Worksheet $sheet)
    {
        $totalTransactions = $this->dailySales->count();
        $totalRevenue = $this->dailySales->sum('total_amount');
        $totalDiscount = $this->dailySales->sum('discount_amount');
        $totalTax = $this->dailySales->sum('tax_amount');

        /* ------------------------------
         * 1. CLINIC NAME (Row 1)
         * ------------------------------ */
        $sheet->mergeCells('A1:I1');
        $sheet->setCellValue('A1', $this->settings['company_name'] ?? 'MADNI EYE CARE CENTER');
        $sheet->getStyle('A1')->applyFromArray([
            'font' => ['bold' => true, 'size' => 20],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
        ]);

        /* ------------------------------
         * 2. Address (Row 2)
         * ------------------------------ */
        $sheet->mergeCells('A2:I2');
        $sheet->setCellValue('A2', $this->settings['company_address'] ?? 'Mehmoodabad Kamila Road Near Tariq Nursery Jhelum');
        $sheet->getStyle('A2')->applyFromArray([
            'font' => ['size' => 12, 'color' => ['argb' => 'FF444444']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
        ]);


        /* ------------------------------
         * 3. Logo (Row 3)
         * ------------------------------ */
        $sheet->mergeCells('A3:I3');
        $sheet->getRowDimension('3')->setRowHeight(66);
        $this->placeImage($sheet);   // Keep your original function

        /* ------------------------------
         * 4. Report Title (Row 4)
         * ------------------------------ */
        $sheet->mergeCells('A4:I4');
        $sheet->setCellValue('A4', 'Daily Sales Report');
        $sheet->getStyle('A4')->applyFromArray([
            'font' => ['bold' => true, 'size' => 14],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
        ]);

        /* ------------------------------
         * 5. Summary Section (Rows 6–9)
         * ------------------------------ */

        // Row 6
        $sheet->setCellValue('A6', 'Generated by:');
        $sheet->setCellValue('B6', auth()->user()->name ?? 'System');
        $sheet->setCellValue('C6', 'Generated date:');
        $sheet->setCellValue('D6', now()->format('F d, Y H:i'));

        // Row 7
        $sheet->setCellValue('A7', 'Total Transactions:');
        $sheet->setCellValue('B7', $totalTransactions);
        $sheet->setCellValue('C7', 'Total Revenue:');
        $sheet->setCellValue('D7', $this->currency_symbol . number_format($totalRevenue, 2));

        // Row 8
        $sheet->setCellValue('A8', 'Total Discount:');
        $sheet->setCellValue('B8', $this->currency_symbol . number_format($totalDiscount, 2));
        $sheet->setCellValue('C8', 'Total Tax:');
        $sheet->setCellValue('D8', $this->currency_symbol . number_format($totalTax, 2));

        /* Style Summary Boxes */
        $sheet->getStyle('A6:D8')->applyFromArray([
//            'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
            'alignment' => ['vertical' => Alignment::VERTICAL_CENTER],
        ]);

        $sheet->getStyle('A6:A8')->getFont()->setBold(true);
        $sheet->getStyle('C6:C8')->getFont()->setBold(true);

        /* ------------------------------
         * 6. HEADER ROW (ROW 11)
         * ------------------------------ */
        $headerRow = 11;

        $sheet->getStyle("A{$headerRow}:I{$headerRow}")->applyFromArray([
            'font' => ['bold' => true, 'color' => ['argb' => 'FFFFFFFF']],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'color' => ['argb' => 'FF305496'], // Blue like screenshot
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
                'vertical' => Alignment::VERTICAL_CENTER,
            ],
            'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
        ]);
        $sheet->getRowDimension($headerRow)->setRowHeight(25);

        /* ------------------------------
         * 7. Data Rows
         * ------------------------------ */
        $start = 12;
        $end = 12 + $this->dailySales->count() - 1;

        // Borders
        $sheet->getStyle("A{$start}:I{$end}")->applyFromArray([
            'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
        ]);

        // Alternating colors
        for ($r = $start; $r <= $end; $r++) {
            if ($r % 2 == 0) {
                $sheet->getStyle("A{$r}:I{$r}")->applyFromArray([
                    'fill' => [
                        'fillType' => Fill::FILL_SOLID,
                        'color' => ['argb' => 'FFF2F2F2'],
                    ],
                ]);
            }
        }

        // --------- A4 print settings (fit to page) ----------
        // Set A4 paper, landscape orientation, fit-to-width
        $pageSetup = $sheet->getPageSetup();
        $pageSetup->setPaperSize(\PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::PAPERSIZE_A4);
        $pageSetup->setOrientation(\PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::ORIENTATION_PORTRAIT);

        // Right align numbers
        $sheet->getStyle("E{$start}:I{$end}")
            ->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);

        // Auto-size all columns
        foreach (range('A', 'I') as $col) {
            $sheet->getColumnDimension($col)->setAutoSize(true);
        }

        return [];
    }


    private function placeImage($sheet)
    {
        $imagePath = public_path('images/clinic-logo.png');
        if (file_exists($imagePath)) {
            $colWidthToPx = function ($width) {
                if (!$width || $width <= 0) $width = 8.43;
                return (int)round($width * 7 + 5);
            };

            $colBWidth = $sheet->getColumnDimension('B')->getWidth();
            $colCWidth = $sheet->getColumnDimension('C')->getWidth();

            if (!$colBWidth) $colBWidth = 8.43;
            if (!$colCWidth) $colCWidth = 8.43;

            $colBWidthPx = $colWidthToPx($colBWidth);
            $colCWidthPx = $colWidthToPx($colCWidth);
            $mergedCellWidthPx = $colBWidthPx + $colCWidthPx;

            $rowHeightPoints = $sheet->getRowDimension(3)->getRowHeight();
            if (!$rowHeightPoints) $rowHeightPoints = 66;
            $rowHeightPx = $rowHeightPoints * 1.333333;

            [$origW, $origH] = getimagesize($imagePath);

            $marginPx = 8;

            $maxWidth = max(1, $mergedCellWidthPx - ($marginPx * 2));
            $maxHeight = max(1, $rowHeightPx - ($marginPx * 2));

            $scaleW = $maxWidth / $origW;
            $scaleH = $maxHeight / $origH;
            $scale = min($scaleW, $scaleH, 1);

            $renderedWidthPx = (int)round($origW * $scale);
            $renderedHeightPx = (int)round($origH * $scale);

            $drawing = new \PhpOffice\PhpSpreadsheet\Worksheet\Drawing();
            $drawing->setName('Clinic Logo');
            $drawing->setDescription('Clinic Logo');
            $drawing->setPath($imagePath);
            $drawing->setWidth($renderedWidthPx);
            $drawing->setCoordinates('D3');

            $offsetX = (int)round(($mergedCellWidthPx - $renderedWidthPx) / 2) + 80;
            $offsetY = (int)round(($rowHeightPx - $renderedHeightPx) / 2);

            $drawing->setOffsetX(max(0, $offsetX));
            $drawing->setOffsetY(max(0, $offsetY));

            $sheet->getStyle('B3')->getAlignment()
                ->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER)
                ->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);

            $drawing->setWorksheet($sheet);
        }
    }

    public function title(): string
    {
        return 'Daily Sales';
    }
}
