<?php

namespace App\Exports;

use App\Models\SystemSetting;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use Maatwebsite\Excel\Events\AfterSheet;
use Carbon\Carbon;

class TransactionExport implements FromCollection, WithHeadings, WithMapping, WithStyles, WithTitle, WithEvents
{
    protected $transactions;
    protected $filters;
    protected $settings;
    protected $currency_symbol;
    protected $dataCount = 0;
    protected $summaryData = [];

    public function __construct($transactions = [], $filters = [])
    {
        $this->transactions = $transactions;
        $this->filters = $filters;
        $this->settings = SystemSetting::getSettings();
        $this->currency_symbol = get_currency_symbol();
        $this->prepareSummaryData();
    }

    protected function prepareSummaryData()
    {
        $this->dataCount = count($this->transactions);

        $totalInflow = 0;
        $totalOutflow = 0;

        foreach ($this->transactions as $transaction) {
            if ($transaction->transaction_type === 'sale' || $transaction->transaction_type === 'payment') {
                $totalInflow += $transaction->amount;
            } else {
                $totalOutflow += $transaction->amount;
            }
        }

        $netTotal = $totalInflow - $totalOutflow;

        $this->summaryData = [
            'total_inflow' => $totalInflow,
            'total_outflow' => $totalOutflow,
            'net_total' => $netTotal,
            'date_generated' => Carbon::now()->format('M d, Y H:i'),
            'generated_by' => auth()->user()->name ?? 'System',
            'transaction_count' => $this->dataCount,
            'start_date' => $this->filters['start_date'] ?? 'N/A',
            'end_date' => $this->filters['end_date'] ?? 'N/A',
            'transaction_type' => $this->filters['type'] ?? 'All Types',
            'payment_method' => $this->filters['payment_method'] ?? 'All Methods'
        ];
    }

    public function collection()
    {
        return collect($this->transactions);
    }

    public function title(): string
    {
        return 'Transactions Report';
    }

    public function headings(): array
    {
        $reportPeriod = $this->getReportPeriod();

        return [
            [$this->settings['company_name'] ?? 'Company Name'],
            [$this->settings['company_address'] ?? ''],
            [''],
            ['Transactions Report'],
            [''],
            ['Report Period:', $reportPeriod],
            ['Date Generated:', $this->summaryData['date_generated']],
            ['Generated by:', $this->summaryData['generated_by']],
            ['Transaction Type:', $this->summaryData['transaction_type']],
            ['Payment Method:', $this->summaryData['payment_method']],
            [''],
            ['Date & Time', 'Type', 'Description', "Amount ({$this->currency_symbol})", 'Payment Method', 'Cashier']
        ];
    }

    public function map($transaction): array
    {
        // Get description based on transaction type
        $description = $transaction->notes ?? 'No description';

        if ($transaction->transaction_type === 'sale' && $transaction->related) {
            $description = 'Sale: ' . ($transaction->related->invoice_number ?? 'N/A');
        } elseif ($transaction->transaction_type === 'refund' && $transaction->related) {
            $description = 'Refund: ' . ($transaction->related->return_number ?? 'N/A');
        }

        // Format amount with sign
        $amount = $transaction->amount;
        if ($transaction->transaction_type === 'refund' || $transaction->transaction_type === 'expense') {
            $amount = -$amount;
        }

        return [
            $transaction->created_at->format('M d, Y H:i'),
            ucfirst($transaction->transaction_type),
            $description,
            (float)$amount,
            ucfirst($transaction->payment_method),
            optional($transaction->user)->name ?? 'System',
        ];
    }

    public function styles(Worksheet $sheet)
    {
        $lastDataRow = $this->dataCount + 12; // 12 rows before data starts

        $styles = [
            // Company name - bold and centered
            1 => [
                'font' => ['bold' => true, 'size' => 16],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER]
            ],

            // Address
            2 => [
                'font' => ['size' => 11],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER]
            ],

            // Row 3 - for image (set vertical alignment)
            'A3:F3' => [
                'alignment' => [
                    'vertical' => Alignment::VERTICAL_CENTER,
                    'horizontal' => Alignment::HORIZONTAL_CENTER,
                ]
            ],
            'A4:F4' => [
                'alignment' => [
                    'vertical' => Alignment::VERTICAL_CENTER,
                    'horizontal' => Alignment::HORIZONTAL_CENTER,
                ]
            ],

            // Report title
            4 => [
                'font' => ['bold' => true, 'size' => 14],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER]
            ],

            // Report info headers
            'A6:A10' => [
                'font' => ['bold' => true]
            ],

            // Data headers
            12 => [
                'font' => ['bold' => true],
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'color' => ['argb' => 'FFE6E6FA']
                ]
            ],

            // Summary section
            ($lastDataRow + 2) => [
                'font' => ['bold' => true, 'size' => 12]
            ],

            // Summary data headers
            'A' . ($lastDataRow + 3) . ':A' . ($lastDataRow + 6) => [
                'font' => ['bold' => true]
            ],

            // Right align amount column
            'D13:D' . $lastDataRow => [
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_RIGHT],
                'numberFormat' => [
                    'formatCode' => '#,##0.00'
                ]
            ],

            // Right align summary numbers
            'B' . ($lastDataRow + 3) . ':B' . ($lastDataRow + 6) => [
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_RIGHT],
                'font' => ['bold' => true],
                'numberFormat' => [
                    'formatCode' => '#,##0.00'
                ]
            ],

            // Set borders for data table
            'A12:F' . $lastDataRow => [
                'borders' => [
                    'allBorders' => [
                        'borderStyle' => Border::BORDER_THIN,
                        'color' => ['argb' => 'FF000000'],
                    ],
                ],
            ],
        ];

        return $styles;
    }

    private function getReportPeriod()
    {
        $startDate = $this->summaryData['start_date'];
        $endDate = $this->summaryData['end_date'];

        if ($startDate === 'N/A' && $endDate === 'N/A') {
            return 'All Time';
        } elseif ($startDate === $endDate) {
            return Carbon::parse($startDate)->format('M d, Y');
        } else {
            $formattedStart = $startDate !== 'N/A' ? Carbon::parse($startDate)->format('M d, Y') : 'Beginning';
            $formattedEnd = $endDate !== 'N/A' ? Carbon::parse($endDate)->format('M d, Y') : 'Now';
            return "{$formattedStart} to {$formattedEnd}";
        }
    }

    private function placeImage($sheet)
    {
        $imagePath = public_path('images/clinic-logo.png');
        if (file_exists($imagePath)) {
            $colWidthToPx = function ($width) {
                if (!$width || $width <= 0) $width = 8.43;
                return (int)round($width * 7 + 5);
            };

            // Calculate total width of merged cells A3:G3
            $totalWidthPx = 0;
            $columns = ['A', 'B', 'C', 'D', 'E', 'F'];

            foreach ($columns as $col) {
                $colWidth = $sheet->getColumnDimension($col)->getWidth();
                if (!$colWidth || $colWidth <= 0) $colWidth = 8.43;
                $totalWidthPx += $colWidthToPx($colWidth);
            }

            $rowHeightPoints = $sheet->getRowDimension(3)->getRowHeight();
            if (!$rowHeightPoints) $rowHeightPoints = 66;
            $rowHeightPx = $rowHeightPoints * 1.333333;

            [$origW, $origH] = getimagesize($imagePath);

            $marginPx = 8;

            $maxWidth = max(1, $totalWidthPx - ($marginPx * 2));
            $maxHeight = max(1, $rowHeightPx - ($marginPx * 2));

            $scaleW = $maxWidth / $origW;
            $scaleH = $maxHeight / $origH;
            $scale = min($scaleW, $scaleH, 1);

            $renderedWidthPx = (int)round($origW * $scale);
            $renderedHeightPx = (int)round($origH * $scale);

            $drawing = new \PhpOffice\PhpSpreadsheet\Worksheet\Drawing();
            $drawing->setName('Clinic Logo');
            $drawing->setDescription('Clinic Logo');
            $drawing->setPath($imagePath);
            $drawing->setWidth($renderedWidthPx);
            $drawing->setCoordinates('C3'); // Start from A3 since cells are merged

            $offsetX = (int)round(($totalWidthPx - $renderedWidthPx) / 2);
            $offsetY = (int)round(($rowHeightPx - $renderedHeightPx) / 2);

            $drawing->setOffsetX(max(0, $offsetX));
            $drawing->setOffsetY(max(0, $offsetY));

            $drawing->setWorksheet($sheet);

            // Style the merged cell A3:G3 for centering
            $sheet->getStyle('A3')->getAlignment()
                ->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER)
                ->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER);

        }
    }

    private function pageLayoutSettings($sheet, $dataEndRow)
    {
        $pageSetup = $sheet->getPageSetup();
        $pageSetup->setPaperSize(\PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::PAPERSIZE_A4);
        $pageSetup->setOrientation(\PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::ORIENTATION_PORTRAIT);
        $pageSetup->setFitToWidth(1);
        $pageSetup->setFitToHeight(0);
        $pageSetup->setFitToPage(true);
        $sheet->getPageSetup()->setPrintArea("A1:F{$dataEndRow}");

        $margins = $sheet->getPageMargins();
        $margins->setTop(0.4);
        $margins->setRight(0.25);
        $margins->setLeft(0.25);
        $margins->setBottom(0.4);
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function(AfterSheet $event) {
                $sheet = $event->sheet->getDelegate();

                // Merge header cells
                $sheet->mergeCells('A1:F1'); // Company name
                $sheet->mergeCells('A2:F2'); // Address
                $sheet->mergeCells('A3:F3'); // Image row
                $sheet->mergeCells('A4:F4'); // Report title
                $sheet->mergeCells('B6:F6'); // Report period
                $sheet->mergeCells('B7:F7'); // Date generated
                $sheet->mergeCells('B8:F8'); // Generated by
                $sheet->mergeCells('B9:F9'); // Transaction type
                $sheet->mergeCells('B10:F10'); // Payment method

                // Set row heights for better image placement
                $sheet->getRowDimension(1)->setRowHeight(30); // Company name row
                $sheet->getRowDimension(2)->setRowHeight(18); // Address row
                $sheet->getRowDimension(3)->setRowHeight(80); // Image row - increased for better visibility
                $sheet->getRowDimension(4)->setRowHeight(25); // Report title row

                // Rest of your existing code...
                $lastDataRow = $this->dataCount + 12;

                // Add summary section
                $sheet->setCellValue('A' . ($lastDataRow + 2), 'SUMMARY');
                $sheet->mergeCells('A' . ($lastDataRow + 2) . ':C' . ($lastDataRow + 2));

                $sheet->setCellValue('A' . ($lastDataRow + 3), 'Total Inflow:');
                $sheet->setCellValue('B' . ($lastDataRow + 3), $this->currency_symbol . number_format($this->summaryData['total_inflow'], 2));

                $sheet->setCellValue('A' . ($lastDataRow + 4), 'Total Outflow:');
                $sheet->setCellValue('B' . ($lastDataRow + 4), $this->currency_symbol . number_format($this->summaryData['total_outflow'], 2));

                $sheet->setCellValue('A' . ($lastDataRow + 5), 'Net Total:');
                $sheet->setCellValue('B' . ($lastDataRow + 5), $this->currency_symbol . number_format($this->summaryData['net_total'], 2));

                $sheet->setCellValue('A' . ($lastDataRow + 6), 'Total Transactions:');
                $sheet->setCellValue('B' . ($lastDataRow + 6), number_format($this->summaryData['transaction_count']));

                // Style summary section
                $sheet->getStyle('A' . ($lastDataRow + 2))->getAlignment()->setHorizontal(Alignment::HORIZONTAL_LEFT);

                $summaryBorderStyle = [
                    'borders' => [
                        'top' => [
                            'borderStyle' => Border::BORDER_MEDIUM,
                            'color' => ['argb' => 'FF000000'],
                        ],
                    ],
                ];

                // Place image - this should now work after setting row heights
                $this->placeImage($sheet);

                $sheet->getStyle('A' . ($lastDataRow + 2) . ':F' . ($lastDataRow + 6))->applyFromArray($summaryBorderStyle);

                // Adjust column widths
                $sheet->getColumnDimension('A')->setWidth(20); // Date & Time
                $sheet->getColumnDimension('B')->setWidth(12); // Type
                $sheet->getColumnDimension('C')->setWidth(30); // Description
                $sheet->getColumnDimension('D')->setWidth(15); // Amount
                $sheet->getColumnDimension('E')->setWidth(20); // Payment Method
                $sheet->getColumnDimension('F')->setWidth(20); // Cashier

                $this->pageLayoutSettings($sheet, $lastDataRow + 6);
            },
        ];
    }
}
